# Generated by Django 5.0.7 on 2024-07-22 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nazwisko')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nazwa')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('round', models.IntegerField(verbose_name='Kolejka')),
                ('home_goals', models.IntegerField(blank=True, null=True, verbose_name='Bramki gospodarze')),
                ('away_goals', models.IntegerField(blank=True, null=True, verbose_name='Bramki goście')),
                ('home_yellow_cards', models.IntegerField(blank=True, null=True, verbose_name='ŻK gospodarze')),
                ('away_yellow_cards', models.IntegerField(blank=True, null=True, verbose_name='ŻK goście')),
                ('home_red_cards', models.IntegerField(blank=True, null=True, verbose_name='CK gospodarze')),
                ('away_red_cards', models.IntegerField(blank=True, null=True, verbose_name='CK goście')),
                ('home_penalty', models.IntegerField(blank=True, null=True, verbose_name='Karne gospodarze')),
                ('away_penalty', models.IntegerField(blank=True, null=True, verbose_name='Karne goście')),
                ('referee_as1', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='referee_as1', to='referee_stats.referee', verbose_name='Sędzia asystent 1')),
                ('referee_as2', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='referee_as2', to='referee_stats.referee', verbose_name='Sędzia asystent 2')),
                ('referee_main', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='referee_main', to='referee_stats.referee', verbose_name='Sędzia główny')),
                ('referee_tech', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='referee_tech', to='referee_stats.referee', verbose_name='Sędzia techniczny')),
                ('referee_var', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='referee_var', to='referee_stats.referee', verbose_name='Sędzia VAR')),
                ('referee_vara', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='referee_vara', to='referee_stats.referee', verbose_name='Sędzia VAR asystent')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='away_team', to='referee_stats.team', verbose_name='Goście')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='home_team', to='referee_stats.team', verbose_name='Gospodarze')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.CharField(max_length=5, verbose_name='Minuta')),
                ('type_of_decision', models.IntegerField(choices=[('1', 'GOOD_PENALTY'), ('2', 'BAD_PENALTY'), ('3', 'MISS_PENALTY'), ('4', 'GOOD_RED_CARD'), ('5', 'BAD_RED_CARD'), ('6', 'MISS_RED_CARD'), ('7', 'OFFSIDE_GOAL'), ('8', 'ONSIDE_GOAL'), ('9', 'OTHER')], verbose_name='Decyzja')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Uwagi')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='match', to='referee_stats.match', verbose_name='Mecz')),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='referee', to='referee_stats.referee', verbose_name='Sędzia')),
            ],
        ),
    ]
