# Generated by Django 5.0.7 on 2024-07-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referee_stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nazwa'),
        ),
    ]
