# Generated by Django 5.0.7 on 2024-07-23 20:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referee_stats', '0005_alter_event_type_of_decision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='additional_minute',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='minute',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)]),
        ),
    ]
